apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: mynginx--with-example
spec:
  environments:
    dev:
      defaultNamespace: default
      server: https://84.201.130.26
    stage:
        defaultNamespace: default
        server: https://178.154.200.233
  vars: {}
