apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - image: cr.yandex/crp4hhqt6ub8aeidjgsk/mynginx:latest
          imagePullPolicy: IfNotPresent
          name: mynginx


---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: mynginx
  type: LoadBalancer